// GENERATED by agent/scripts/build-edge-n8n.mjs — do not edit by hand.
// Edge-side n8n templates + merge + validate (INTEGRATION_PLAN §3 Wave 4 #15).
// Merger/validator ported verbatim from agent/src/n8n (unit-tested); templates
// mirror agent/n8n_templates/*.json (drift-guarded). Pure + Web-API-only (Deno-safe).

export interface N8nNode {
  id: string;
  name: string;
  type: string;
  typeVersion: number;
  position: [number, number];
  parameters: Record<string, unknown>;
  credentials?: Record<string, { id: string; name: string }>;
  webhookId?: string;
}
export type N8nConnections = Record<string, { main: Array<Array<{ node: string; type: "main"; index: number }>> }>;
export interface N8nWorkflow {
  name: string;
  meta: Record<string, unknown>;
  nodes: N8nNode[];
  connections: N8nConnections;
  active: boolean;
  settings: Record<string, unknown>;
  staticData: null | Record<string, unknown>;
  pinData: Record<string, unknown>;
}
export type PlaceholderMap = Record<string, string>;
export interface ValidationResult { valid: boolean; errors: string[] }

function fillStringPlaceholders(value: string, map: PlaceholderMap): string {
  return value.replace(/__([A-Z0-9_]+)__/g, (full, key) => {
    const mapKey = `__${key}__`;
    return mapKey in map ? map[mapKey]! : full;
  });
}
function fillValue(value: unknown, map: PlaceholderMap): unknown {
  if (typeof value === "string") return fillStringPlaceholders(value, map);
  if (Array.isArray(value)) return value.map((v) => fillValue(v, map));
  if (value !== null && typeof value === "object") {
    const result: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(value as Record<string, unknown>)) result[k] = fillValue(v, map);
    return result;
  }
  return value;
}
function reposition(nodes: N8nNode[]): N8nNode[] {
  const X_START = 240, X_STEP = 220, Y = 300;
  return nodes.map((node, i) => ({ ...node, position: [X_START + i * X_STEP, Y] as [number, number] }));
}

export function mergeWorkflow(template: N8nWorkflow, placeholders: PlaceholderMap): N8nWorkflow {
  const nodes: N8nNode[] = template.nodes.map((node) => {
    const merged: N8nNode = {
      ...node,
      id: crypto.randomUUID(),
      parameters: fillValue(node.parameters, placeholders) as Record<string, unknown>,
    };
    if (node.credentials) merged.credentials = fillValue(node.credentials, placeholders) as Record<string, { id: string; name: string }>;
    if (node.webhookId) merged.webhookId = crypto.randomUUID();
    return merged;
  });
  const connections: N8nConnections = {};
  for (const [fromName, targets] of Object.entries(template.connections)) {
    connections[fromName] = { main: targets.main.map((output) => output.map((t) => ({ ...t }))) };
  }
  return { ...template, nodes: reposition(nodes), connections, active: false };
}

const PLACEHOLDER_RE = /__[A-Z0-9_]+__/;
function scanForUnresolved(value: unknown, path: string, found: string[]): void {
  if (typeof value === "string") {
    const match = value.match(/__([A-Z0-9_]+)__/g);
    if (match) for (const m of match) found.push(`${path}: unresolved placeholder ${m}`);
    return;
  }
  if (Array.isArray(value)) { for (let i = 0; i < value.length; i++) scanForUnresolved(value[i], `${path}[${i}]`, found); return; }
  if (value !== null && typeof value === "object") {
    for (const [k, v] of Object.entries(value as Record<string, unknown>)) scanForUnresolved(v, `${path}.${k}`, found);
  }
}
export function validateWorkflow(workflow: unknown): ValidationResult {
  const errors: string[] = [];
  if (!workflow || typeof workflow !== "object") return { valid: false, errors: ["workflow is not an object"] };
  const w = workflow as Partial<N8nWorkflow>;
  if (!w.name || typeof w.name !== "string" || w.name.trim() === "") errors.push("workflow.name is missing or empty");
  if (!Array.isArray(w.nodes) || w.nodes.length === 0) {
    errors.push("workflow.nodes must be a non-empty array");
  } else {
    const nodeNames = new Set<string>();
    for (let i = 0; i < w.nodes.length; i++) {
      const node = w.nodes[i];
      if (!node || typeof node !== "object") { errors.push(`nodes[${i}]: not an object`); continue; }
      if (!node.id || typeof node.id !== "string") errors.push(`nodes[${i}]: missing id`);
      else if (PLACEHOLDER_RE.test(node.id)) errors.push(`nodes[${i}]: id is still a placeholder: ${node.id}`);
      if (!node.name || typeof node.name !== "string") errors.push(`nodes[${i}]: missing name`);
      else { if (nodeNames.has(node.name)) errors.push(`nodes[${i}]: duplicate node name "${node.name}"`); nodeNames.add(node.name); }
      if (!node.type || typeof node.type !== "string") errors.push(`nodes[${i}]: missing type`);
      if (typeof node.typeVersion !== "number" || node.typeVersion < 1) errors.push(`nodes[${i}]: typeVersion must be >= 1`);
      if (!Array.isArray(node.position) || node.position.length !== 2) errors.push(`nodes[${i}]: position must be [x, y]`);
      if (!node.parameters || typeof node.parameters !== "object") errors.push(`nodes[${i}]: parameters must be an object`);
    }
    if (w.connections && typeof w.connections === "object") {
      for (const [connFrom, targets] of Object.entries(w.connections)) {
        if (!nodeNames.has(connFrom)) errors.push(`connections: source node "${connFrom}" not in nodes`);
        if (!targets || !Array.isArray(targets.main)) continue;
        for (const output of targets.main) for (const target of output) {
          if (!nodeNames.has(target.node)) errors.push(`connections: target node "${target.node}" not in nodes`);
        }
      }
    }
  }
  if (!w.connections || typeof w.connections !== "object") errors.push("workflow.connections must be an object");
  if (Array.isArray(w.nodes)) {
    const unresolved: string[] = [];
    for (let i = 0; i < w.nodes.length; i++) scanForUnresolved(w.nodes[i]!.parameters, `nodes[${i}].parameters`, unresolved);
    errors.push(...unresolved);
  }
  return { valid: errors.length === 0, errors };
}

export const TEMPLATES: Record<string, N8nWorkflow> = {
  "form-to-crm": {
  "name": "Form to CRM",
  "meta": {
    "templateId": "scout-form-to-crm",
    "n8nVersion": "1.88.0"
  },
  "nodes": [
    {
      "parameters": {
        "formTitle": "__FORM_TITLE__",
        "formDescription": "__FORM_DESCRIPTION__",
        "formFields": {
          "values": [
            { "fieldLabel": "Full Name", "fieldType": "text", "requiredField": true },
            { "fieldLabel": "Email", "fieldType": "email", "requiredField": true },
            { "fieldLabel": "Company", "fieldType": "text", "requiredField": true },
            { "fieldLabel": "Message", "fieldType": "textarea", "requiredField": false }
          ]
        },
        "responseMode": "lastNode"
      },
      "id": "__NODE_ID_1__",
      "name": "Form Trigger",
      "type": "n8n-nodes-base.formTrigger",
      "typeVersion": 2,
      "position": [240, 300],
      "webhookId": "__WEBHOOK_ID__"
    },
    {
      "parameters": {
        "jsCode": "// Map form fields to CRM contact schema\nconst f = $input.first().json;\nreturn [{\n  json: {\n    firstName: (f['Full Name'] || '').split(' ')[0],\n    lastName: (f['Full Name'] || '').split(' ').slice(1).join(' '),\n    email: f['Email'],\n    company: f['Company'],\n    notes: f['Message'] || '',\n    source: '__FORM_TITLE__',\n    createdAt: new Date().toISOString()\n  }\n}];"
      },
      "id": "__NODE_ID_2__",
      "name": "Map to CRM Schema",
      "type": "n8n-nodes-base.code",
      "typeVersion": 2,
      "position": [460, 300]
    },
    {
      "parameters": {
        "method": "POST",
        "url": "__CRM_API_ENDPOINT__",
        "authentication": "predefinedCredentialType",
        "nodeCredentialType": "httpHeaderAuth",
        "sendHeaders": true,
        "headerParameters": {
          "parameters": [{ "name": "Authorization", "value": "Bearer __CRM_API_KEY__" }]
        },
        "sendBody": true,
        "contentType": "json",
        "body": "={{ JSON.stringify($json) }}"
      },
      "id": "__NODE_ID_3__",
      "name": "Create CRM Contact",
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 4,
      "position": [680, 300]
    },
    {
      "parameters": {
        "respondWith": "text",
        "responseBody": "Thank you! We will be in touch shortly."
      },
      "id": "__NODE_ID_4__",
      "name": "Confirm Submission",
      "type": "n8n-nodes-base.respondToWebhook",
      "typeVersion": 1,
      "position": [900, 300]
    }
  ],
  "connections": {
    "Form Trigger": { "main": [[{ "node": "Map to CRM Schema", "type": "main", "index": 0 }]] },
    "Map to CRM Schema": { "main": [[{ "node": "Create CRM Contact", "type": "main", "index": 0 }]] },
    "Create CRM Contact": { "main": [[{ "node": "Confirm Submission", "type": "main", "index": 0 }]] }
  },
  "active": false,
  "settings": { "executionOrder": "v1" },
  "staticData": null,
  "pinData": {}
},
  "inbound-email-triage": {
  "name": "Inbound Email Triage",
  "meta": {
    "templateId": "scout-inbound-email-triage",
    "n8nVersion": "1.88.0"
  },
  "nodes": [
    {
      "parameters": {
        "pollTimes": {
          "item": [{ "mode": "everyMinute" }]
        },
        "filters": {
          "readStatus": "unread",
          "sender": "__FILTER_SENDER_DOMAIN__"
        }
      },
      "id": "__NODE_ID_1__",
      "name": "Email Trigger (IMAP)",
      "type": "n8n-nodes-base.emailReadImap",
      "typeVersion": 2,
      "position": [240, 300],
      "credentials": { "imap": { "id": "__CRED_IMAP__", "name": "IMAP account" } }
    },
    {
      "parameters": {
        "jsCode": "// Classify email intent and extract entities\nconst email = $input.first().json;\nconst subject = (email.subject || '').toLowerCase();\nconst body = (email.text || email.html || '').replace(/<[^>]+>/g, ' ').slice(0, 2000);\n\nlet category = 'general';\nif (/demo|trial|pricing|quote/.test(subject + body)) category = 'sales';\nelse if (/bug|error|issue|broken|down/.test(subject + body)) category = 'support';\nelse if (/partner|integration|api/.test(subject + body)) category = 'partnerships';\n\nreturn [{\n  json: {\n    from: email.from?.value?.[0]?.address || '',\n    subject: email.subject || '',\n    body: body,\n    category,\n    receivedAt: new Date().toISOString()\n  }\n}];"
      },
      "id": "__NODE_ID_2__",
      "name": "Classify Email",
      "type": "n8n-nodes-base.code",
      "typeVersion": 2,
      "position": [460, 300]
    },
    {
      "parameters": {
        "method": "POST",
        "url": "__SCOUT_WEBHOOK_URL__",
        "authentication": "predefinedCredentialType",
        "nodeCredentialType": "httpHeaderAuth",
        "sendHeaders": true,
        "headerParameters": {
          "parameters": [
            { "name": "x-scout-signature", "value": "__HMAC_SIGNATURE__" },
            { "name": "x-scout-timestamp", "value": "={{ Date.now() }}" }
          ]
        },
        "sendBody": true,
        "contentType": "json",
        "body": "={{ JSON.stringify({ event: 'email_triage', data: $json }) }}"
      },
      "id": "__NODE_ID_3__",
      "name": "Send to Scout",
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 4,
      "position": [680, 300]
    },
    {
      "parameters": {
        "select": "channel",
        "channelId": { "__rl": true, "value": "__SLACK_CHANNEL_ID__", "mode": "id" },
        "text": ":email: New *{{ $json.category }}* email from `{{ $json.from }}`\n*Subject:* {{ $json.subject }}\nRun: `{{ $json.run_id }}`"
      },
      "id": "__NODE_ID_4__",
      "name": "Notify Slack",
      "type": "n8n-nodes-base.slack",
      "typeVersion": 2,
      "position": [900, 300],
      "credentials": { "slackApi": { "id": "__CRED_SLACK_API__", "name": "Slack account" } }
    }
  ],
  "connections": {
    "Email Trigger (IMAP)": { "main": [[{ "node": "Classify Email", "type": "main", "index": 0 }]] },
    "Classify Email": { "main": [[{ "node": "Send to Scout", "type": "main", "index": 0 }]] },
    "Send to Scout": { "main": [[{ "node": "Notify Slack", "type": "main", "index": 0 }]] }
  },
  "active": false,
  "settings": { "executionOrder": "v1" },
  "staticData": null,
  "pinData": {}
},
  "rag-faq-skeleton": {
  "name": "RAG FAQ Skeleton",
  "meta": {
    "templateId": "scout-rag-faq-skeleton",
    "n8nVersion": "1.88.0"
  },
  "nodes": [
    {
      "parameters": {
        "httpMethod": "POST",
        "path": "__WEBHOOK_PATH__",
        "responseMode": "lastNode",
        "options": {}
      },
      "id": "__NODE_ID_1__",
      "name": "Question Webhook",
      "type": "n8n-nodes-base.webhook",
      "typeVersion": 2,
      "position": [240, 300],
      "webhookId": "__WEBHOOK_ID__"
    },
    {
      "parameters": {
        "jsCode": "// Build embedding request from incoming question\nconst payload = $input.first().json;\nconst question = (payload.question || '').trim();\nif (!question) throw new Error('Missing question field');\nreturn [{ json: { question, sessionId: payload.sessionId || crypto.randomUUID() } }];"
      },
      "id": "__NODE_ID_2__",
      "name": "Validate Input",
      "type": "n8n-nodes-base.code",
      "typeVersion": 2,
      "position": [460, 300]
    },
    {
      "parameters": {
        "method": "POST",
        "url": "__EMBEDDING_API_URL__",
        "authentication": "predefinedCredentialType",
        "nodeCredentialType": "httpHeaderAuth",
        "sendHeaders": true,
        "headerParameters": {
          "parameters": [
            { "name": "Authorization", "value": "Bearer __EMBEDDING_API_KEY__" }
          ]
        },
        "sendBody": true,
        "contentType": "json",
        "body": "={{ JSON.stringify({ input: $json.question, model: '__EMBEDDING_MODEL__' }) }}"
      },
      "id": "__NODE_ID_3__",
      "name": "Embed Question",
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 4,
      "position": [680, 300]
    },
    {
      "parameters": {
        "method": "POST",
        "url": "__VECTOR_STORE_SEARCH_URL__",
        "authentication": "predefinedCredentialType",
        "nodeCredentialType": "httpHeaderAuth",
        "sendHeaders": true,
        "headerParameters": {
          "parameters": [
            { "name": "Authorization", "value": "Bearer __VECTOR_STORE_KEY__" }
          ]
        },
        "sendBody": true,
        "contentType": "json",
        "body": "={{ JSON.stringify({ vector: $json.data[0].embedding, topK: 5, namespace: '__VECTOR_NAMESPACE__' }) }}"
      },
      "id": "__NODE_ID_4__",
      "name": "Retrieve Context",
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 4,
      "position": [900, 300]
    },
    {
      "parameters": {
        "jsCode": "// Compile retrieved chunks into a context block\nconst matches = $input.first().json.matches || [];\nconst context = matches.map((m, i) => `[${i+1}] ${m.metadata?.text || ''}`).join('\\n\\n');\nconst question = $('Validate Input').first().json.question;\nreturn [{ json: { question, context, sessionId: $('Validate Input').first().json.sessionId } }];"
      },
      "id": "__NODE_ID_5__",
      "name": "Build Context",
      "type": "n8n-nodes-base.code",
      "typeVersion": 2,
      "position": [1120, 300]
    },
    {
      "parameters": {
        "method": "POST",
        "url": "__LLM_API_URL__",
        "authentication": "predefinedCredentialType",
        "nodeCredentialType": "httpHeaderAuth",
        "sendHeaders": true,
        "headerParameters": {
          "parameters": [
            { "name": "Authorization", "value": "Bearer __LLM_API_KEY__" }
          ]
        },
        "sendBody": true,
        "contentType": "json",
        "body": "={{ JSON.stringify({ model: '__LLM_MODEL__', max_tokens: 512, messages: [{ role: 'user', content: 'Context:\\n' + $json.context + '\\n\\nQuestion: ' + $json.question }] }) }}"
      },
      "id": "__NODE_ID_6__",
      "name": "Generate Answer",
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 4,
      "position": [1340, 300]
    },
    {
      "parameters": {
        "respondWith": "json",
        "responseBody": "={{ JSON.stringify({ answer: $json.content[0].text, sessionId: $('Build Context').first().json.sessionId }) }}"
      },
      "id": "__NODE_ID_7__",
      "name": "Return Answer",
      "type": "n8n-nodes-base.respondToWebhook",
      "typeVersion": 1,
      "position": [1560, 300]
    }
  ],
  "connections": {
    "Question Webhook": { "main": [[{ "node": "Validate Input", "type": "main", "index": 0 }]] },
    "Validate Input": { "main": [[{ "node": "Embed Question", "type": "main", "index": 0 }]] },
    "Embed Question": { "main": [[{ "node": "Retrieve Context", "type": "main", "index": 0 }]] },
    "Retrieve Context": { "main": [[{ "node": "Build Context", "type": "main", "index": 0 }]] },
    "Build Context": { "main": [[{ "node": "Generate Answer", "type": "main", "index": 0 }]] },
    "Generate Answer": { "main": [[{ "node": "Return Answer", "type": "main", "index": 0 }]] }
  },
  "active": false,
  "settings": { "executionOrder": "v1" },
  "staticData": null,
  "pinData": {}
},
  "scheduled-scrape-summarize-notify": {
  "name": "Scheduled Scrape, Summarise & Notify",
  "meta": {
    "templateId": "scout-scheduled-scrape-summarize-notify",
    "n8nVersion": "1.88.0"
  },
  "nodes": [
    {
      "parameters": {
        "rule": {
          "interval": [{ "field": "cronExpression", "expression": "__CRON_SCHEDULE__" }]
        }
      },
      "id": "__NODE_ID_1__",
      "name": "Schedule Trigger",
      "type": "n8n-nodes-base.scheduleTrigger",
      "typeVersion": 1,
      "position": [240, 300]
    },
    {
      "parameters": {
        "method": "GET",
        "url": "__TARGET_URL__",
        "options": { "timeout": 30000 }
      },
      "id": "__NODE_ID_2__",
      "name": "Fetch Page",
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 4,
      "position": [460, 300]
    },
    {
      "parameters": {
        "jsCode": "// Extract main content from HTML\nconst html = $input.first().json.data || '';\nconst text = html.replace(/<[^>]+>/g, ' ').replace(/\\s+/g, ' ').slice(0, 4000);\nreturn [{ json: { content: text, fetchedAt: new Date().toISOString() } }];"
      },
      "id": "__NODE_ID_3__",
      "name": "Extract Content",
      "type": "n8n-nodes-base.code",
      "typeVersion": 2,
      "position": [680, 300]
    },
    {
      "parameters": {
        "method": "POST",
        "url": "__SCOUT_WEBHOOK_URL__",
        "authentication": "predefinedCredentialType",
        "nodeCredentialType": "httpHeaderAuth",
        "sendHeaders": true,
        "headerParameters": {
          "parameters": [
            { "name": "x-scout-signature", "value": "__HMAC_SIGNATURE__" },
            { "name": "x-scout-timestamp", "value": "={{ Date.now() }}" }
          ]
        },
        "sendBody": true,
        "bodyParameters": {
          "parameters": [
            { "name": "url", "value": "__TARGET_URL__" },
            { "name": "notes", "value": "={{ $json.content.slice(0, 500) }}" }
          ]
        }
      },
      "id": "__NODE_ID_4__",
      "name": "Trigger Scout Discovery",
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 4,
      "position": [900, 300]
    },
    {
      "parameters": {
        "select": "channel",
        "channelId": { "__rl": true, "value": "__SLACK_CHANNEL_ID__", "mode": "id" },
        "text": "Scout discovery triggered for __TARGET_URL__\nRun ID: {{ $json.run_id }}"
      },
      "id": "__NODE_ID_5__",
      "name": "Notify Slack",
      "type": "n8n-nodes-base.slack",
      "typeVersion": 2,
      "position": [1120, 300],
      "credentials": { "slackApi": { "id": "__CRED_SLACK_API__", "name": "Slack account" } }
    }
  ],
  "connections": {
    "Schedule Trigger": { "main": [[{ "node": "Fetch Page", "type": "main", "index": 0 }]] },
    "Fetch Page": { "main": [[{ "node": "Extract Content", "type": "main", "index": 0 }]] },
    "Extract Content": { "main": [[{ "node": "Trigger Scout Discovery", "type": "main", "index": 0 }]] },
    "Trigger Scout Discovery": { "main": [[{ "node": "Notify Slack", "type": "main", "index": 0 }]] }
  },
  "active": false,
  "settings": { "executionOrder": "v1" },
  "staticData": null,
  "pinData": {}
},
  "webhook-enrich-store": {
  "name": "Webhook Enrich & Store",
  "meta": {
    "templateId": "scout-webhook-enrich-store",
    "n8nVersion": "1.88.0"
  },
  "nodes": [
    {
      "parameters": {
        "httpMethod": "POST",
        "path": "__WEBHOOK_PATH__",
        "responseMode": "lastNode",
        "options": {}
      },
      "id": "__NODE_ID_1__",
      "name": "Webhook",
      "type": "n8n-nodes-base.webhook",
      "typeVersion": 2,
      "position": [240, 300],
      "webhookId": "__WEBHOOK_ID__"
    },
    {
      "parameters": {
        "jsCode": "// Normalise and enrich incoming payload\nconst payload = $input.first().json;\nreturn [{\n  json: {\n    url: (payload.url || '').trim().toLowerCase(),\n    notes: payload.notes || '',\n    receivedAt: new Date().toISOString(),\n    source: 'webhook'\n  }\n}];"
      },
      "id": "__NODE_ID_2__",
      "name": "Normalise Payload",
      "type": "n8n-nodes-base.code",
      "typeVersion": 2,
      "position": [460, 300]
    },
    {
      "parameters": {
        "method": "POST",
        "url": "__SCOUT_WEBHOOK_URL__",
        "authentication": "predefinedCredentialType",
        "nodeCredentialType": "httpHeaderAuth",
        "sendHeaders": true,
        "headerParameters": {
          "parameters": [
            { "name": "x-scout-signature", "value": "__HMAC_SIGNATURE__" },
            { "name": "x-scout-timestamp", "value": "={{ Date.now() }}" }
          ]
        },
        "sendBody": true,
        "contentType": "json",
        "body": "={{ JSON.stringify($json) }}"
      },
      "id": "__NODE_ID_3__",
      "name": "Send to Scout",
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 4,
      "position": [680, 300]
    },
    {
      "parameters": {
        "respondWith": "json",
        "responseBody": "={{ JSON.stringify({ status: 'accepted', run_id: $json.run_id }) }}"
      },
      "id": "__NODE_ID_4__",
      "name": "Respond 202",
      "type": "n8n-nodes-base.respondToWebhook",
      "typeVersion": 1,
      "position": [900, 300]
    }
  ],
  "connections": {
    "Webhook": { "main": [[{ "node": "Normalise Payload", "type": "main", "index": 0 }]] },
    "Normalise Payload": { "main": [[{ "node": "Send to Scout", "type": "main", "index": 0 }]] },
    "Send to Scout": { "main": [[{ "node": "Respond 202", "type": "main", "index": 0 }]] }
  },
  "active": false,
  "settings": { "executionOrder": "v1" },
  "staticData": null,
  "pinData": {}
}
};
