// Minimal Supabase type stubs for the web layer.
// Full codegen types are regenerated by `supabase gen types` after P17 deploy.

export type Database = {
  public: {
    Tables: {
      runs: {
        Row: {
          id: string;
          org_id: string;
          status: string;
          next_node: string;
          submitted_url: string;
          normalized_url: string;
          idempotency_key: string;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["runs"]["Row"], "id" | "created_at"> & {
          id?: string;
        };
      };
    };
    Functions: Record<string, unknown>;
  };
};
