import { describe, it, expect } from "vitest";
import { readFileSync, readdirSync } from "node:fs";
import { dirname, resolve, join } from "node:path";
import { fileURLToPath } from "node:url";

// Verified-by-proxy guard for the Edge n8n module (Wave 4 #15). The Edge runs on
// Deno (not runnable here), so we can't unit-test supabase/functions/agent/n8n.ts
// directly. Instead: the merger/validator there are ported verbatim from agent/src
// (unit-tested) and the template DATA is GENERATED from agent/n8n_templates/*.json.
// This asserts the embedded templates are byte-identical to the canonical files,
// so the Edge merge+validate behaves like the tested agent/src path.

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "../../..");
const templatesDir = resolve(repoRoot, "agent/n8n_templates");

describe("Edge n8n module mirrors canonical templates (no drift)", () => {
  const edge = readFileSync(resolve(repoRoot, "supabase/functions/agent/n8n.ts"), "utf8");
  const files = readdirSync(templatesDir).filter((f) => f.endsWith(".json") && f !== "index.json");

  it("is the generated, do-not-edit module", () => {
    expect(edge).toContain("GENERATED by agent/scripts/build-edge-n8n.mjs");
    expect(edge).toContain("export function mergeWorkflow");
    expect(edge).toContain("export function validateWorkflow");
  });

  it.each(files)("embeds %s byte-identically", (file) => {
    const canonical = readFileSync(join(templatesDir, file), "utf8").trim();
    expect(edge.includes(canonical)).toBe(true);
  });
});
