import { describe, it, expect } from "vitest";
import { readFileSync, readdirSync } from "node:fs";
import { dirname, resolve, join } from "node:path";
import { fileURLToPath } from "node:url";
import { mergeWorkflow } from "./merger.js";
import { validateWorkflow } from "./validator.js";
import type { N8nWorkflow, PlaceholderMap } from "./types.js";

// Hermetic n8n import smoke test (INTEGRATION_PLAN §3 Wave 4 #17) — closes the
// long-open P8 "CI import smoke test" item without a live n8n: every shipped
// archetype, once placeholders are filled and node ids/positions regenerated by
// the merger, validates structurally (nodes/connections/typeVersion, no
// unresolved placeholders). The deeper node-schema check via czlonkowski/n8n-mcp
// runs in CI (.github/workflows/evals.yml) — see docs/RUNBOOK.md / the vendor
// PROVENANCE note.

const here = dirname(fileURLToPath(import.meta.url));
const templatesDir = resolve(here, "../../n8n_templates");

// Fill every non-id placeholder with a concrete value (ids/webhooks are
// regenerated by the merger, so leave __NODE_ID_n__ / __WEBHOOK_ID__ alone).
function fullPlaceholderMap(template: N8nWorkflow): PlaceholderMap {
  const json = JSON.stringify(template);
  const map: PlaceholderMap = {};
  for (const m of json.matchAll(/__([A-Z0-9_]+)__/g)) {
    const full = m[0];
    if (/^__NODE_ID_\d+__$/.test(full) || full === "__WEBHOOK_ID__") continue;
    map[full] = "configured-value";
  }
  return map;
}

const files = readdirSync(templatesDir).filter((f) => f.endsWith(".json") && f !== "index.json");

describe("n8n template importability (closes P8 smoke test, hermetic)", () => {
  it.each(files)("%s merges + validates cleanly", (file) => {
    const template = JSON.parse(readFileSync(join(templatesDir, file), "utf8")) as N8nWorkflow;
    const merged = mergeWorkflow(template, fullPlaceholderMap(template));
    const result = validateWorkflow(merged);
    expect(result.errors).toEqual([]);
    expect(result.valid).toBe(true);
  });
});
