insert into public.tools (
  id,
  name,
  category,
  pillars,
  what_it_does,
  best_for,
  integrates_with,
  effort,
  cost_tier,
  notes,
  enabled
) values
('microsoft-365-copilot', 'Microsoft 365 Copilot', 'AI productivity', array['Operations & Efficiency', 'Customer Experience & Marketing'], 'Adds AI assistance across Microsoft 365 workspaces.', array['knowledge work acceleration', 'meeting summaries', 'document drafting'], array['Teams', 'Outlook', 'SharePoint'], 2, 'paid', 'Best when the client is already Microsoft 365-heavy.', true),
('copilot-studio', 'Copilot Studio', 'Agent builder', array['Customer Experience & Marketing', 'Operations & Efficiency'], 'Builds enterprise copilots and conversational workflows.', array['internal copilots', 'customer self-service', 'FAQ assistants'], array['Microsoft 365', 'Power Platform', 'Dataverse'], 3, 'paid', 'Use for Microsoft-native agent surfaces.', true),
('power-automate', 'Power Automate', 'Automation', array['Operations & Efficiency'], 'Automates Microsoft-centric workflows and approvals.', array['approval flows', 'document routing', 'Teams alerts'], array['SharePoint', 'Outlook', 'Dataverse', 'Teams'], 2, 'paid', 'Primary Microsoft workflow option.', true),
('power-apps', 'Power Apps', 'Low-code app', array['Operations & Efficiency'], 'Creates lightweight internal business apps.', array['intake apps', 'field forms', 'simple CRUD workflows'], array['Dataverse', 'SharePoint', 'Power Automate'], 3, 'paid', 'Good for consultant-approved internal tooling.', true),
('power-bi', 'Power BI', 'Analytics', array['Data & Decision Intelligence'], 'Builds dashboards and semantic business reporting.', array['KPI reporting', 'executive dashboards', 'operational analytics'], array['Fabric', 'Snowflake', 'Excel'], 2, 'paid', 'Pairs well with Microsoft data estates.', true),
('microsoft-teams', 'Microsoft Teams', 'Collaboration', array['Operations & Efficiency'], 'Collaboration and notification surface for Microsoft organizations.', array['alerts', 'approvals', 'team workflows'], array['Power Automate', 'SharePoint', 'Copilot'], 1, 'paid', 'Use as notification and adoption channel.', true),
('sharepoint', 'SharePoint', 'Content platform', array['Operations & Efficiency', 'Cybersecurity & Risk Management'], 'Stores documents, intranet content, and lists.', array['document workflows', 'knowledge bases', 'controlled document storage'], array['Teams', 'Power Automate', 'Microsoft 365'], 2, 'paid', 'Common source for document-heavy automations.', true),
('dataverse', 'Dataverse', 'Data platform', array['Operations & Efficiency', 'Data & Decision Intelligence'], 'Managed data layer for Power Platform applications.', array['low-code databases', 'Power Apps backends', 'governed records'], array['Power Apps', 'Power Automate', 'Power BI'], 3, 'paid', 'Use when governance matters in Power Platform.', true),
('microsoft-fabric', 'Microsoft Fabric', 'Data platform', array['Data & Decision Intelligence'], 'Unified Microsoft analytics and lakehouse platform.', array['data warehousing', 'BI modernization', 'lakehouse analytics'], array['Power BI', 'Azure', 'Microsoft 365'], 4, 'paid', 'Microsoft-native analytics modernization path.', true),
('azure-functions', 'Azure Functions', 'Serverless', array['Operations & Efficiency'], 'Runs event-driven functions in Azure.', array['API glue', 'webhooks', 'scheduled jobs'], array['Azure', 'Microsoft 365', 'Power Platform'], 3, 'paid', 'Good when client already has Azure controls.', true),
('azure-ai', 'Azure AI', 'AI platform', array['Data & Decision Intelligence', 'Customer Experience & Marketing'], 'Enterprise AI services and model hosting in Azure.', array['AI apps', 'document intelligence', 'enterprise model governance'], array['Azure Functions', 'Microsoft Fabric'], 4, 'paid', 'Use for Azure-governed AI deployments.', true),
('aws-lambda', 'AWS Lambda', 'Serverless', array['Operations & Efficiency'], 'Runs serverless functions for event-driven automation.', array['API glue', 'background jobs', 'data processing'], array['AWS', 'API Gateway', 'S3'], 3, 'paid', 'Alternative for AWS-first clients.', true),
('supabase', 'Supabase', 'Backend platform', array['Operations & Efficiency', 'Data & Decision Intelligence'], 'Provides Postgres, auth, storage, realtime, and Edge Functions.', array['fast prototypes', 'internal apps', 'agent persistence'], array['Vercel', 'n8n', 'Postgres'], 3, 'free-tier', 'Core Scout backend.', true),
('vercel', 'Vercel', 'Frontend hosting', array['Operations & Efficiency'], 'Hosts Next.js web applications and thin APIs.', array['frontend deployments', 'share pages', 'serverless API routes'], array['Supabase', 'Next.js'], 2, 'free-tier', 'Core Scout web host.', true),
('netlify', 'Netlify', 'Frontend hosting', array['Operations & Efficiency'], 'Hosts static and serverless web projects.', array['marketing sites', 'lightweight apps', 'forms'], array['GitHub', 'serverless functions'], 2, 'free-tier', 'Alternative frontend host when Vercel is not preferred.', true),
('n8n', 'n8n', 'Automation', array['Operations & Efficiency'], 'Builds workflow automations with APIs and webhooks.', array['lead routing', 'data sync', 'notification workflows'], array['Supabase', 'Slack', 'Teams', 'HTTP APIs'], 3, 'free-software', 'Primary generated workflow artifact in Scout.', true),
('make', 'Make', 'Automation', array['Operations & Efficiency'], 'Visual automation platform for SaaS integrations.', array['SaaS workflow automation', 'lightweight integrations'], array['CRM', 'Slack', 'Google Workspace'], 2, 'paid', 'Alternative no-code automation platform.', true),
('zapier', 'Zapier', 'Automation', array['Operations & Efficiency'], 'Simple SaaS automation and trigger-action workflows.', array['quick SaaS zaps', 'notification automations'], array['CRM', 'Slack', 'Forms'], 1, 'paid', 'Use for simple non-technical workflows.', true),
('snowflake', 'Snowflake', 'Data platform', array['Data & Decision Intelligence'], 'Cloud data warehouse and analytics platform.', array['data platform modernization', 'governed analytics', 'AI-ready data'], array['Power BI', 'dbt', 'Microsoft Fabric'], 4, 'paid', 'NorthBound is a Snowflake Services Partner.', true),
('postgres', 'Postgres', 'Database', array['Data & Decision Intelligence', 'Operations & Efficiency'], 'Relational database for transactional and analytical workloads.', array['operational data stores', 'app databases', 'reporting marts'], array['Supabase', 'Metabase', 'n8n'], 3, 'free-tier', 'Strong default data store for prototypes.', true),
('airtable', 'Airtable', 'Low-code database', array['Operations & Efficiency'], 'Spreadsheet-like database for business teams.', array['intake trackers', 'lightweight CRM', 'content operations'], array['Zapier', 'Make', 'n8n'], 2, 'paid', 'Good bridge from spreadsheet workflows.', true),
('metabase', 'Metabase', 'Analytics', array['Data & Decision Intelligence'], 'Open-source BI and dashboarding.', array['internal dashboards', 'self-service analytics'], array['Postgres', 'Snowflake'], 2, 'free-software', 'Useful when Power BI is not required.', true),
('hex', 'Hex', 'Analytics', array['Data & Decision Intelligence'], 'Collaborative notebooks and analytics apps.', array['data science workflows', 'analytics apps'], array['Snowflake', 'dbt', 'Python'], 3, 'paid', 'Good for advanced analytics teams.', true),
('claude-api', 'Claude API', 'LLM', array['Data & Decision Intelligence', 'Operations & Efficiency'], 'Claude models for structured reasoning and generation.', array['agent reasoning', 'summarization', 'structured output'], array['LangGraph', 'Supabase Edge Functions'], 3, 'paid', 'Scout uses Claude for analysis.', true),
('openai-api', 'OpenAI API', 'LLM', array['Data & Decision Intelligence'], 'OpenAI models for AI app features.', array['chatbots', 'classification', 'generation'], array['Azure OpenAI', 'LangChain'], 3, 'paid', 'Alternative model provider.', true),
('langgraph', 'LangGraph', 'Agent framework', array['Operations & Efficiency'], 'Builds durable, stateful agent graphs.', array['multi-step agents', 'checkpointed workflows'], array['Claude API', 'Postgres'], 4, 'free-software', 'Scout agent orchestration layer.', true),
('mcp', 'Model Context Protocol', 'AI integration', array['Operations & Efficiency'], 'Exposes tools and data sources to AI assistants.', array['Claude Code tools', 'agent integrations'], array['Claude Code', 'TypeScript'], 3, 'free-software', 'Scout ships an MCP server.', true),
('pgvector', 'pgvector', 'Vector search', array['Data & Decision Intelligence'], 'Adds vector embeddings to Postgres.', array['RAG prototypes', 'semantic search'], array['Supabase', 'Postgres'], 3, 'free-software', 'Future-ready RAG option.', true),
('pinecone', 'Pinecone', 'Vector database', array['Data & Decision Intelligence'], 'Managed vector search service.', array['production semantic search', 'RAG at scale'], array['OpenAI', 'LangChain'], 3, 'paid', 'Use when managed vector operations are needed.', true),
('jina-reader', 'Jina Reader', 'Scraping', array['Operations & Efficiency'], 'Converts public web pages to markdown for analysis.', array['site discovery', 'content extraction'], array['HTTP clients', 'LLM prompts'], 1, 'free', 'Scout primary scrape path.', true),
('firecrawl', 'Firecrawl', 'Scraping', array['Operations & Efficiency'], 'Scrapes and crawls web pages into clean markdown.', array['hard-to-scrape sites', 'crawl jobs'], array['LLM agents'], 2, 'free-tier', 'Optional fallback behind env guard.', true),
('tavily', 'Tavily', 'Search', array['Data & Decision Intelligence'], 'Search API for AI applications.', array['web research', 'source discovery'], array['LLM agents'], 2, 'paid', 'Optional research extension.', true),
('dynamics-365', 'Dynamics 365', 'CRM/ERP', array['Customer Experience & Marketing', 'Operations & Efficiency'], 'Microsoft CRM and business applications suite.', array['sales workflows', 'service operations', 'ERP integration'], array['Power Platform', 'Teams', 'Outlook'], 4, 'paid', 'Microsoft-native CRM/ERP path.', true),
('hubspot', 'HubSpot', 'CRM', array['Customer Experience & Marketing'], 'CRM and marketing automation platform.', array['lead management', 'marketing workflows', 'sales operations'], array['n8n', 'Zapier', 'Slack'], 2, 'paid', 'Common SMB CRM integration target.', true),
('salesforce', 'Salesforce', 'CRM', array['Customer Experience & Marketing'], 'Enterprise CRM platform.', array['sales automation', 'service workflows', 'pipeline reporting'], array['MuleSoft', 'Tableau', 'Slack'], 4, 'paid', 'Use for Salesforce-heavy enterprises.', true),
('slack', 'Slack', 'Collaboration', array['Operations & Efficiency'], 'Team messaging and workflow notifications.', array['alerts', 'approval prompts', 'operations notifications'], array['n8n', 'Zapier', 'GitHub'], 1, 'free-tier', 'Companion workflow notification option.', true),
('notion', 'Notion', 'Knowledge base', array['Operations & Efficiency'], 'Docs, wiki, and lightweight database workspace.', array['playbooks', 'project notes', 'knowledge bases'], array['Slack', 'Zapier', 'n8n'], 2, 'free-tier', 'Good for documentation outputs.', true),
('asana', 'Asana', 'Project management', array['Operations & Efficiency'], 'Project and task management.', array['implementation plans', 'task routing'], array['Slack', 'Zapier', 'n8n'], 2, 'paid', 'Useful for delivery playbooks.', true),
('monday', 'Monday.com', 'Work management', array['Operations & Efficiency'], 'Configurable work management boards and automations.', array['operations boards', 'project tracking'], array['Slack', 'Make', 'Zapier'], 2, 'paid', 'Alternative work management platform.', true),
('jira', 'Jira', 'Issue tracking', array['Operations & Efficiency'], 'Software delivery and ticket tracking.', array['technical implementation tasks', 'bug workflows'], array['GitHub', 'Slack', 'Confluence'], 2, 'paid', 'Useful for technical delivery teams.', true),
('github', 'GitHub', 'Developer platform', array['Operations & Efficiency', 'Cybersecurity & Risk Management'], 'Source control, automation, and CI/CD.', array['repo workflows', 'CI checks', 'deployment pipelines'], array['Actions', 'Slack', 'Vercel'], 2, 'free-tier', 'Scout uses GitHub Actions.', true),
('intercom', 'Intercom', 'Customer support', array['Customer Experience & Marketing'], 'Customer messaging and support automation.', array['support triage', 'customer engagement'], array['Slack', 'HubSpot', 'Zendesk'], 3, 'paid', 'Good fit for customer-facing automation.', true),
('zendesk', 'Zendesk', 'Customer support', array['Customer Experience & Marketing'], 'Support ticketing and customer service workflows.', array['ticket triage', 'knowledge base', 'support analytics'], array['Slack', 'Salesforce', 'n8n'], 3, 'paid', 'Common support automation target.', true)
on conflict (id) do update set
  name = excluded.name,
  category = excluded.category,
  pillars = excluded.pillars,
  what_it_does = excluded.what_it_does,
  best_for = excluded.best_for,
  integrates_with = excluded.integrates_with,
  effort = excluded.effort,
  cost_tier = excluded.cost_tier,
  notes = excluded.notes,
  enabled = excluded.enabled,
  updated_at = now();
