// Read-only public view of a shared report — strips internal data.

interface ReportPublic {
  id: string;
  summary: string;
  business_profile: Record<string, unknown>;
  opportunities: unknown[];
  ranked?: unknown[];
  discovery_questions: unknown[];
  created_at: string;
}

export function PublicReportView({ report }: { report: ReportPublic }) {
  const profile = report.business_profile as { name?: string; industry?: string; description?: string } | null;
  // Consistent with the report viewer/PDF: the ranked list is canonical (Wave 6 de-dup).
  const opps = ((report.ranked?.length ? report.ranked : report.opportunities) ?? []) as Array<{
    id: string; title: string; pillar: string; impactScore: number; quadrant: string;
  }>;

  return (
    <main className="shell">
      <article className="rise">
        <header>
          <span className="eyebrow">Shared report · read only</span>
          <h1>{profile?.name ?? "Discovery Report"}</h1>
          {profile?.industry && <p className="lead">{profile.industry}</p>}
        </header>

        <section>
          <h2>Executive summary</h2>
          <p style={{ marginBottom: 0 }}>{report.summary}</p>
        </section>

        {profile && (
          <section>
            <h2>Company overview</h2>
            <p style={{ marginBottom: 0 }}>{profile.description}</p>
          </section>
        )}

        <section>
          <h2>Ranked opportunities</h2>
          {opps.length === 0 && <div className="empty">No opportunities identified.</div>}
          <ul className="opps">
            {opps.map((opp) => (
              <li key={opp.id} className="opp">
                <h3 style={{ margin: 0 }}>{opp.title}</h3>
                <div className="opp__badges">
                  <span className="badge badge--tint pillar" data-pillar={opp.pillar}>{opp.pillar}</span>
                  <span className="badge badge--tint quadrant" data-q={opp.quadrant}>{opp.quadrant}</span>
                </div>
                <p className="dim" style={{ margin: 0 }}>Impact {opp.impactScore}/5</p>
              </li>
            ))}
          </ul>
        </section>

        <footer>
          <p className="meta" style={{ margin: 0 }}>Generated by Scout · NorthBound Advisory</p>
        </footer>
      </article>
    </main>
  );
}
