// Read-only public view of a shared report — strips internal data.

interface ReportPublic {
  id: string;
  summary: string;
  business_profile: Record<string, unknown>;
  opportunities: unknown[];
  ranked?: unknown[];
  discovery_questions: unknown[];
  created_at: string;
}

export function PublicReportView({ report }: { report: ReportPublic }) {
  const profile = report.business_profile as { name?: string; industry?: string; description?: string } | null;
  // Consistent with the report viewer/PDF: the ranked list is canonical (Wave 6 de-dup).
  const opps = ((report.ranked?.length ? report.ranked : report.opportunities) ?? []) as Array<{
    id: string; title: string; pillar: string; impactScore: number; quadrant: string;
  }>;

  return (
    <article>
      <header>
        <h1>{profile?.name ?? "Discovery Report"}</h1>
        <p>Shared report — read only</p>
      </header>

      <section>
        <h2>Summary</h2>
        <p>{report.summary}</p>
      </section>

      {profile && (
        <section>
          <h2>Company Overview</h2>
          <p>{profile.description}</p>
          {profile.industry && <p>Industry: {profile.industry}</p>}
        </section>
      )}

      <section>
        <h2>Opportunities</h2>
        {opps.length === 0 && <p>No opportunities identified.</p>}
        <ol>
          {opps.map((opp) => (
            <li key={opp.id}>
              <strong>{opp.title}</strong> — {opp.pillar} (impact {opp.impactScore}/5, {opp.quadrant})
            </li>
          ))}
        </ol>
      </section>

      <footer>
        <p>Generated by Scout · NorthBound Advisory</p>
      </footer>
    </article>
  );
}
